name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.0.9
        with:
          host: ${{ secrets.SSH_HOST_ADDR }}
          port: 22
          username: ${{ secrets.SSH_HOST_USER }}
          key: ${{ secrets.SSH_PRIV_KEY }}
          script: echo "Done!"
